services:
  redis:
    image: redis:7-alpine
    container_name: nestjs-redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  redis_data:
